# Generated by Django 4.2.3 on 2024-04-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ahuzot_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("gps_latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("gps_longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("start_parking_day_weekday", models.TimeField()),
                ("end_parking_night_weekday", models.TimeField()),
                (
                    "daily_rate_weekday",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "hourly_rate_day_weekday",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "night_rate_weekday",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "hourly_rate_night_weekday",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("start_parking_day_friday", models.TimeField(blank=True, null=True)),
                ("end_parking_night_friday", models.TimeField(blank=True, null=True)),
                (
                    "daily_rate_friday",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hourly_rate_day_friday",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "night_rate_friday",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hourly_rate_night_friday",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("start_parking_day_saturday", models.TimeField(blank=True, null=True)),
                ("end_parking_night_saturday", models.TimeField(blank=True, null=True)),
                (
                    "daily_rate_saturday",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hourly_rate_day_saturday",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "night_rate_saturday",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hourly_rate_night_saturday",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("resident_discount", models.FloatField(default=0.0)),
                (
                    "close_to_home",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "usually_occupied_during",
                    models.CharField(blank=True, max_length=255),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(default="123", max_length=10)),
                (
                    "preferences",
                    models.CharField(
                        choices=[("WALK_LESS", "ללכת פחות"), ("PAY_LESS", "לשלם פחות")],
                        default="WALK_LESS",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=25)),
                ("parking_area", models.CharField(max_length=2)),
            ],
        ),
    ]
