# Generated by Django 4.2.3 on 2024-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersetting",
            name="preferences",
            field=models.CharField(default="WALK_LESS", max_length=20),
        ),
    ]
