# Generated by Django 4.2.3 on 2024-05-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recommendation", "0002_alter_usersetting_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersetting",
            name="preferences",
            field=models.CharField(default="Walk less", max_length=20),
        ),
    ]
