# Generated by Django 4.2.3 on 2024-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recommendation", "0003_alter_usersetting_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("distance", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
            ],
        ),
    ]
