# Generated by Django 5.0.6 on 2024-06-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0004_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='ahuzot_code',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='close_to_home',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='daily_rate_friday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='daily_rate_saturday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='daily_rate_weekday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='end_parking_night_friday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='end_parking_night_saturday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='end_parking_night_weekday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='gps_latitude',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='gps_longitude',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='hourly_rate_night_friday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='hourly_rate_night_saturday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='hourly_rate_night_weekday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='night_rate_friday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='night_rate_saturday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='night_rate_weekday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='resident_discount',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='start_parking_day_friday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='start_parking_day_saturday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='start_parking_day_weekday',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='usually_occupied_during',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='achuzat_code',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='daily_night_rate_friday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='daily_night_rate_saturday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='daily_night_rate_weekday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='daily_rate_day_friday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='daily_rate_day_saturday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='daily_rate_day_weekday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='day_hour_friday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='day_hour_saturday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='day_hour_weekday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='hourly_night_rate_friday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='hourly_night_rate_saturday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='hourly_night_rate_weekday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='hourly_rate_day_friday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='hourly_rate_day_saturday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='hourly_rate_day_weekday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
