# Generated by Django 5.0.6 on 2024-06-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0005_remove_parkinglot_ahuzot_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='achuzat_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='close_to_home',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='resident_discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
