# Generated by Django 5.0.6 on 2024-06-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0006_rename_achuzat_code_parkinglot_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='close_to_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='daily_night_rate_friday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='daily_night_rate_saturday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='daily_night_rate_weekday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='daily_rate_day_friday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='daily_rate_day_saturday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='daily_rate_day_weekday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='hourly_night_rate_friday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='hourly_night_rate_saturday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='hourly_night_rate_weekday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='hourly_rate_day_friday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='hourly_rate_day_saturday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='hourly_rate_day_weekday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='resident_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
