# Generated by Django 5.0.6 on 2024-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0007_alter_parkinglot_close_to_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='preferences',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
