# Generated by Django 5.0.6 on 2024-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0009_alter_parkinglot_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='preferences',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='parking_area',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='parking_area',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
