# Generated by Django 5.0.6 on 2024-06-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0010_remove_usersetting_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='default_address',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='default_preferences',
            field=models.CharField(choices=[('pay-less', 'Pay Less'), ('walk-less', 'Walk Less')], default=None, max_length=150),
        ),
    ]
