# Generated by Django 4.2.3 on 2024-08-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recommendation", "0012_userhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersetting",
            name="id",
        ),
        migrations.AddField(
            model_name="usersetting",
            name="birth_year",
            field=models.IntegerField(default=1990),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="F",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="user_id",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
