# Generated by Django 4.2.3 on 2024-08-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Recommendation",
            "0013_remove_usersetting_id_usersetting_birth_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersetting",
            name="birth_year",
            field=models.IntegerField(default=None),
        ),
    ]
