# Generated by Django 4.2.3 on 2024-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recommendation", "0014_alter_usersetting_birth_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettingAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
