# Generated by Django 4.2.3 on 2024-08-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Recommendation", "0015_usersettingadmin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSettingAdmin",
        ),
    ]
