# Generated by Django 4.2.3 on 2024-08-09 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Recommendation", "0016_delete_usersettingadmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference",
                    models.CharField(
                        choices=[("pay-less", "Pay Less"), ("walk-less", "Walk Less")],
                        max_length=50,
                    ),
                ),
                (
                    "parking_preference_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "parking_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Recommendation.parkinglot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserParkingRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                (
                    "parking_preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Recommendation.parkingpreference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParkingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_datetime", models.DateTimeField(auto_now_add=True)),
                ("search_address", models.CharField(max_length=255)),
                (
                    "preference",
                    models.CharField(
                        choices=[("pay-less", "Pay Less"), ("walk-less", "Walk Less")],
                        max_length=50,
                    ),
                ),
                ("parking_duration", models.CharField(max_length=50)),
                ("walking_time_1", models.IntegerField()),
                ("walking_time_2", models.IntegerField(blank=True, null=True)),
                ("walking_time_3", models.IntegerField(blank=True, null=True)),
                (
                    "final_choice",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recommendation_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_1",
                        to="Recommendation.parkinglot",
                    ),
                ),
                (
                    "recommendation_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_2",
                        to="Recommendation.parkinglot",
                    ),
                ),
                (
                    "recommendation_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_3",
                        to="Recommendation.parkinglot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
