# Generated by Django 5.0.6 on 2024-08-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0017_parkingpreference_userparkingrating_parkinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='walking_time_1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
