# Generated by Django 5.0.6 on 2024-08-12 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0018_alter_parkinghistory_walking_time_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recommendation.usersetting'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recommendation.usersetting'),
        ),
        migrations.AlterField(
            model_name='userparkingrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recommendation.usersetting'),
        ),
    ]
