# Generated by Django 5.0.6 on 2024-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0019_alter_parkinghistory_user_alter_userhistory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='search_datetime',
            field=models.DateTimeField(),
        ),
    ]
