# Generated by Django 5.0.6 on 2024-08-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0020_alter_parkinghistory_search_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='search_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
