# Generated by Django 5.0.6 on 2024-08-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0021_alter_parkinghistory_search_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinghistory',
            old_name='user',
            new_name='user_id',
        ),
    ]
