# Generated by Django 5.0.6 on 2024-08-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0022_rename_user_parkinghistory_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinghistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
