# Generated by Django 5.0.6 on 2024-08-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0023_rename_user_id_parkinghistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='search_datetime',
            field=models.DateTimeField(),
        ),
    ]
