# Generated by Django 4.2.3 on 2024-08-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Recommendation", "0024_alter_parkinghistory_search_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkinghistory",
            name="final_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="final_choice",
                to="Recommendation.parkinglot",
            ),
        ),
    ]
