# Generated by Django 5.0.6 on 2024-08-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0025_alter_parkinghistory_final_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinghistory',
            name='walking_time_1',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='walking_time_2',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='walking_time_3',
        ),
    ]
