# Generated by Django 5.0.6 on 2024-09-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0027_alter_parkinghistory_preference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
